$(document).ready(function(){var e="small",zf=$(".has-sidebar").width();$(".zoom").click(function(){"small"==e?($(".zoom").html('<i class="fa fa-compress"></i> Zoom-'),$(".has-sidebar").animate({width:"100%"}),$(".sidebar").css("display","none"),e="large"):"large"==e&&($(".zoom").html('<i class="fa fa-compress"></i> Zoom+'),$(".has-sidebar").width(zf),$(".sidebar").css("display","inherit"),e="small")});function d(a){$(".change-tab ul li").removeClass("l_active"),$(a).addClass("l_active");$('.box-popular').addClass('spinner');var a=$(".get-popular.l_active").attr("data-type");var b=$(".get-popular.l_active").attr("data-postnum");$.post(ajaxurl,{sidebar_post:1,type:a,postnum:b},function(data){if(data==0)data='1';$('.popular-post').html(data);$('.box-popular').removeClass('spinner');});}
var a=$("#video").attr("data-id"),c=$("#video").attr("data-sv");a&&server(c,a),$("#server1").click(function(){$("li.bt_active").removeClass("bt_active"),$("#server1").addClass("bt_active"),$("#video").attr("data-sv","1")}),$("#server2").click(function(){$("li.bt_active").removeClass("bt_active"),$("#server2").addClass("bt_active"),$("#video").attr("data-sv","2")}),$(".btn-like").click(function(){var a=$(this).data("id");$("span.vote-count").removeClass("fa-thumbs-up"),$("span.vote-count").addClass("fa-thumbs-up"),a&&$.post(ajaxurl,{like_post:1,id:a},function(a){0==a&&(a="1"),$(".vote-count").html(a)})}),$(".btn-dislike").dblclick(function(){var a=$(this).data("id");$("span.vote-countd").removeClass("fa-thumbs-down"),$("span.vote-countd").addClass("fa-thumbs-down"),a&&$.post(ajaxurl,{dislike:1,id:a},function(a){0==a&&(a="1"),$(".vote-countd").html(a)})}),$(".dp-popular-tab li").click(function(){return d(this),!1}),($(".dp-popular-tab li:first-child")),$(".button-menu").click(function(){$(".button-menu").hasClass("active")&&$(".body.row").hasClass("blur")?$(".body.row").removeClass("blur"):$(".body.row").addClass("blur"),$(this).toggleClass("active"),$(".list-menu").toggleClass("active")}),$(".button-search").click(function(){$(".button-search").hasClass("active")&&$(".body.row").hasClass("blur")?$(".body.row").removeClass("blur"):$(".body.row").addClass("blur"),$(this).toggleClass("active"),$(".form-search").toggleClass("active")}),$(".list-menu, .button-menu, .form-search, .button-search, .sub-menu>li").click(function(a){a.stopPropagation()}),$("html, .button-search, .form-search").click(function(){$(".button-menu").hasClass("active")&&!$(".button-search").hasClass("active")&&$(".body.row").removeClass("blur"),$(".list-menu").removeClass("active"),$(".button-menu").removeClass("active")}),$("html, .button-menu, .list-menu").click(function(){$(".button-search").hasClass("active")&&!$(".button-menu").hasClass("active")&&$(".body.row").removeClass("blur"),$(".form-search").removeClass("active"),$(".button-search").removeClass("active")}),$("li.item-menu").click(function(){$(this).toggleClass("active")}),$(".item-content-toggle").click(function(){"Xem th\xeam"==$(this).find(".show-more").html()?$(this).find(".show-more").html("Thu g\u1ECDn"):$(this).find(".show-more").html("Xem th\xeam"),$("article").toggleClass("toggled")});var b=$("#video").attr("post-id");b&&$.post(ajaxurl,{views_post:1,id_bv:b})
function xd(str){str=str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g,"a");str=str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g,"e");str=str.replace(/ì|í|ị|ỉ|ĩ/g,"i");str=str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g,"o");str=str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g,"u");str=str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g,"y");str=str.replace(/đ/g,"d");str=str.replace(/À|Á|Ạ|Ả|Ã|Â|Ầ|Ấ|Ậ|Ẩ|Ẫ|Ă|Ằ|Ắ|Ặ|Ẳ|Ẵ/g,"A");str=str.replace(/È|É|Ẹ|Ẻ|Ẽ|Ê|Ề|Ế|Ệ|Ể|Ễ/g,"E");str=str.replace(/Ì|Í|Ị|Ỉ|Ĩ/g,"I");str=str.replace(/Ò|Ó|Ọ|Ỏ|Õ|Ô|Ồ|Ố|Ộ|Ổ|Ỗ|Ơ|Ờ|Ớ|Ợ|Ở|Ỡ/g,"O");str=str.replace(/Ù|Ú|Ụ|Ủ|Ũ|Ư|Ừ|Ứ|Ự|Ử|Ữ/g,"U");str=str.replace(/Ỳ|Ý|Ỵ|Ỷ|Ỹ/g,"Y");str=str.replace(/Đ/g,"D");str=str.replace(/([^\w ]|_)/g,"");return str;}
$('#form-search').submit(function(){var kw=xd($('#keyword').val());kw=$.trim(kw);kw=kw.replace(/\ /gi,'-');if(kw){window.location.href='/search/'+kw+'/';}
return false;});var f=document.location.pathname.match(/^\/search\/([^\/]+-[^\/]+)\//)
if(f){f=f[1]
var f2=localStorage['f:'+f]
if(f2&&f2<Math.round(new Date().getTime()/1000)){}else{f2=0}
if(!f2){$.post(ajaxurl,{history:f},function(data){try{var jsons=JSON.parse(data);if(jsons.success)
localStorage['f:'+f]=Math.round(new Date().getTime()/1000)}catch(e){}});}}});var reloadedCount={};function reloadCurrentserver(){var a=$("#video").attr("data-id"),b=$("#video").attr("data-sv");a&&server(b,a)}
function del_cache(){var a=$("#video").attr("data-id"),b=$("#video").attr("data-sv");$.post(ajaxurl,{delcache:1,server:b,videoid:a})}
function errorHandler(){var b=$("#video").attr("data-id"),a=$("#video").attr("data-sv");void 0===reloadedCount[a]&&(reloadedCount[a]=1),reloadedCount[a]<2?(setTimeout(function(){reloadCurrentserver()},100),reloadedCount[a]++):($.post(ajaxurl,{reloadError:1,server:a,videoid:b}),$("#video .video-player").html("<p style='background:#333; color: #fff; text-align:center; padding: 10px;'>Server n\xe0y l\xe0 l\u1ED7i v\xe0 t\u1EF1 \u0111\u1ED9ng t\u1EA3i l\u1EA1i trong 2 l\u1EA7n.<br />Vui l\xf2ng ch\u1ECDn m\u1ED9t server #2 \u0111\u1EC3 xem. </p>"))}
var cookie_notice=!1,error_thispage=!1;function server(a,b){var b=parseInt(b),a=parseInt(a);return $.post(ajaxurl,{vl3x_server:1,id:b,server:a},function(c){var b=JSON.parse(c);$("#video").html(b.player),$(".download-button").html(b.download),1==a&&$("#server1").addClass("bt_active")}),!1}